### ISSUE TITLE
message to restart keeps coming op even after restarting (obviously)

### ISSUE THREAD

**Issue by Uffje** [davidfor/calibre-annotations#10]
For some reason calibre keeps asking me to restart calibre before I can customize Annotations plug in. I reverted back to the latest 4.xx version and back to 5.xx a few days ago, but after a reinstall of the plugin there was no change.

I am using:
- Calibre 5.7.2
- macOS 11.1 Big Sur
- English (United Kingdom)
- Latest 1.13 plug in

**Comment by nareddyt** [comment]
Calibre 5.6.0 works with this plugin. There was some code removal in calibre 5.7.0 that breaks the plugin startup.

https://github.com/kovidgoyal/calibre/commit/18c97430bbf580289e829570a63e105871a3328f#diff-c2710ab650b3e7c17270e0c5c4e590823aad6bf3a0f8b5ef09af7f5579125a2f

```
Traceback (most recent call last):
  File "calibre\gui2\ui.py", line 134, in __init__
  File "calibre\gui2\ui.py", line 152, in init_iaction
  File "calibre\customize\__init__.py", line 614, in load_actual_plugin
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.annotations.action", line 51, in <module>
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.annotations.annotated_books", line 39, in <module>
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.annotations.common_utils", line 54, in <module>
ImportError: cannot import name 'RC' from 'calibre.utils.ipc' (C:\Program Files\Calibre2\app\bin\python-lib.bypy.frozen\calibre\utils\ipc\__init__.pyc)
```

**Comment by Uffje** [comment]
Would it be best to downgrade then or will there be a fix?

**Comment by nareddyt** [comment]
I'm not sure, I am not the maintainer of this plugin. I downgraded for now.

**Comment by Uffje** [comment]
I realised I was using the wrong annotation button, because it was still not working on 5.6 and did a reinstall and found the yellow annotation button. Tried to update to 5.8 and to see if it worked after a reinstall of the plug-in, but it did not, so probably missing the same lines.

**Comment by davidfor** [comment]
This will be fixed in the next release. It is a change in calibre that I didn't realize would affect the plugin. And it only had an affect because I hadn't cleaned up some code that was not being used.

**Comment by Uffje** [comment]
Just tested in 5.8.1 with 1.14 and it works again, thanks for the fix and I will close this issue.

**Comment by dbogdanov** [comment]
I am having the same problem on Calibre 7.6.0 with the latest plugin version 1.17.13.  Maybe this issue can be reopened.
